apiVersion: apps/v1
kind: Deployment
metadata:
  name: projapp
  labels:
    app: projapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projapp
  template:
    metadata:
      labels:
        app: projapp
    spec:
      containers:
      - name: projapp
        image: 545018635250.dkr.ecr.us-east-1.amazonaws.com/projapp:test3
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Test"
        volumeMounts:
        - name: settings
          mountPath: /app/settings
          readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
      - name: settings
        secret:
          secretName: k8s-appsettings