apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-notification
  labels:
    app: proj-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj-notification
  template:
    metadata:
      labels:
        app: proj-notification
    spec:
      containers:
      - name: proj-notification
        image: 545018635250.dkr.ecr.us-east-1.amazonaws.com/proj-notification:test4
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Test"
      imagePullSecrets:
        - name: regcred